[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
headless = true

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff" 
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
